---
title: Dave's Homepage
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-tactile
description: Bookmark this to keep an eye on my project updates!
